var name = prompt("Ismingizni kiriting")
console.log('Sizning ismingiz ' + name)
var age = prompt("Yoshingizni kiriting")
console.log('Yoshingiz ' + age + ' da')
var misol1 = +prompt('8+5=?')
console.log('8+5=' + misol1 + '. Javob: 13')
var misol2 = +prompt('5*5=?')
console.log('5*5=' + misol2 + '. Javob: 25')
var misol3 = +prompt('5/5=?')
console.log('5/5=' + misol3 + '. Javob: 1')
var misol4 = +prompt('8+5=?')
console.log('8+5=' + misol4 + '. Javob: 13')
var misol5 = +prompt('5-5=?')
console.log('5-5=' + misol5 + '. Javob: 0')
var misol6 = +prompt('5+5=?')
console.log('5+5=' + misol6 + '. Javob: 10')
var misol7 = +prompt('8%5=?')
console.log('qoldiq: ' + misol7 + '. Javob: 3')
var misol8 = +prompt('8/4=?')
console.log('8:4=' + misol8 + '. Javob: 2')
var misol9 = +prompt('8*5=?')
console.log('8*5=' + misol9 + '. Javob: 40')
var misol10 = +prompt('8-5=?')
console.log('8-5=' + misol10 + '. Javob: 3')
alert('Console ga oting')